apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: awe4100gd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: awe4100gd-go 
  name: awe4100gd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: awe4100gd-go 
